modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/JensenJ-Modding/YouShallNotGrief/issues"
license = "MIT License"

[[mods]]
modId = "youshallnotgrief"
version = "${version}"
displayName = "You Shall Not Grief"
authors = "JensenJ"
description = '''
Adds logging utilities used to catch griefers and thieves.
'''
logoFile = "logo.png"

[[dependencies.youshallnotgrief]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.youshallnotgrief]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.youshallnotgrief]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.youshallnotgrief]]
modId = "sqlite_jdbc"
mandatory = true
versionRange = "[3.41.2.1,)"
ordering = "AFTER"
side = "BOTH"