# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.1.2
maven_group = net.youshallnotgrief
archives_name = youshallnotgrief
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Multiplatform Dependencies
architectury_api_version = 13.0.8
sqlite_version = 3.49.1.0+2025-04-20
mixin_extras_version=0.4.1

# Fabric Dependencies
fabric_loader_version = 0.16.9
fabric_api_version = 0.116.0
forge_config_api_port_version=21.1.3
night_config_version=3.6.5
# Runtime testing Dependencies
mod_menu_version = 11.0.3

# NeoForge Dependencies
neoforge_version = 21.1.172
# Runtime testing dependencies
create_version = 6.0.6-98
ponder_version = 1.0.56
flywheel_version = 1.0.4
registrate_version = MC1.21-1.3.0+62
ae2_version = 19.0.4-alpha