modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/JensenJ-Modding/YouShallNotGrief/issues"
license = "MIT License"

[[mods]]
modId = "youshallnotgrief"
version = "${version}"
displayName = "You Shall Not Grief"
authors = "JensenJ"
description = '''
Adds logging utilities used to catch griefers and thieves.
'''
logoFile = "logo.png"

[[dependencies.youshallnotgrief]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.youshallnotgrief]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.youshallnotgrief]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "youshallnotgrief-neoforge.mixins.json"

[[mixins]]
config = "youshallnotgrief-common.mixins.json"