plugins {
    id 'com.gradleup.shadow'
}

repositories {
    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    maven { url = "https://mvn.devos.one/snapshots" } // Registrate
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" } // ForgeConfigAPIPort
    maven { url = "https://api.modrinth.com/maven" }
    maven {
        name = "Modmaven"
        url = uri("https://modmaven.dev/")

        content {
            includeGroup("appeng")
        }
    }

    //This is for the jdbc driver which isn't available on a maven yet
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    // SQLite Driver - The one on modrinth doesn't work with NeoForge yet, so we are using a hard linked one here
    // This file is from https://github.com/jblemee/minecraft-sqlite-jdbc/releases/tag/v1.21-neoforge
    modImplementation(include name: 'sqlite-jdbc-3.49.1.0+2025-04-30-all')

    //Dependencies for testing
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    implementation("net.createmod.ponder:Ponder-NeoForge-${minecraft_version}:${ponder_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    implementation("com.tterrag.registrate:Registrate:${registrate_version}")

    modImplementation "appeng:appliedenergistics2-neoforge:${ae2_version}"
}

apply from: 'https://raw.githubusercontent.com/JensenJ-Modding/Mod-Resources/refs/heads/main/1.21.1/Gradle/neoforge-build.gradle'
