name: Testing

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build the mod
        run: ./gradlew build

      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            common/build/libs/
            fabric/build/libs/
            forge/build/libs/
